# # Install pre-commit hooks via
# pre-commit install

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: check-yaml

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  - id: yapf

- repo: local
  hooks:
  - id: prospector
    language: system
    types: [file, python]
    name: prospector
    description: "This hook runs Prospector: https://github.com/landscapeio/prospector"
    entry: prospector
