language: python
python:
- "2.7"
- "3.6"

node_js:
- 7

cache: pip

before_install:
# Upgrade pip setuptools and wheel
- pip install --upgrade pip

install:
- pip install -e .[pre-commit]

script:
- ./prepare.sh
